// src/pages/home/Home.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useRoute } from 'vue-router'
import { usePosts, type Lang } from '../../composables/usePosts'
import PostItem from '../../components/post-item/PostItem.vue'
import { useHead } from '@unhead/vue'

const route = useRoute()
const lang = computed<Lang>(() => (route.meta.lang as Lang) ?? 'es')
const posts = computed(() => usePosts(lang.value))
const linkPrefix = computed(() => (lang.value === 'en' ? '/en/' : '/'))

useHead({
  title: '',
})
</script>

<template>
  <div class="post">
    <div v-for="post in posts" :key="post.meta.slug">
      <RouterLink :to="`${linkPrefix}${post.meta.slug}`">
        <PostItem :post="post" :lang="lang" />
      </RouterLink>
    </div>
  </div>
</template>

// src/pages/home/Home.tsx
import { Link } from 'react-router-dom'
import { usePosts, type Lang } from '../../hooks/usePosts'
import PostItem from '../../components/post-item/PostItem'

interface HomeProps {
  lang?: Lang
}

export default function Home({ lang = 'es' }: HomeProps) {
  const posts = usePosts(lang)
  const linkPrefix = lang === 'en' ? '/en/' : '/'

  return (
    <div className="post">
      {posts.map((post) => (
        <div key={post.meta.slug}>
          <Link to={`${linkPrefix}${post.meta.slug}`}>
            <PostItem post={post} lang={lang} />
          </Link>
        </div>
      ))}
    </div>
  )
}
