// src/pages/post/Post.tsx
import { useState, type MouseEvent } from 'react'
import { Link, useParams } from 'react-router-dom'
import { usePosts, type Lang } from '../../hooks/usePosts'
import { formattedDate } from '../../utils/date'
import './Post.css'

interface PostProps {
  lang?: Lang
}

export default function Post({ lang = 'es' }: PostProps) {
  const { slug } = useParams()
  const posts = usePosts(lang)
  const backLink = lang === 'en' ? '/en' : '/'
  const linkPrefix = lang === 'en' ? '/en/' : '/'
  const dateLocale = lang === 'en' ? 'en-US' : 'es-CL'

  const currentIndex = posts.findIndex((p) => p.meta.slug === slug)
  const post = currentIndex === -1 ? undefined : posts[currentIndex]

  // posts are sorted newest-first, so "previous" (older) is the next index
  // and "next" (newer) is the previous index
  const previousPost = posts[currentIndex + 1]
  const nextPost = currentIndex > 0 ? posts[currentIndex - 1] : undefined

  const [isFullscreen, setIsFullscreen] = useState(false)

  function handleClick(event: MouseEvent<HTMLDivElement>) {
    const target = event.target as HTMLImageElement

    if (target.tagName === 'IMG') {
      const next = !isFullscreen
      setIsFullscreen(next)
      document.body.style.overflow = next ? 'hidden' : ''
      document.body.classList.toggle('enlarged', next)
      target.classList.toggle('enlarged', next)
    }
  }

  if (!post) {
    return (
      <div className="post">
        <div>{lang === 'en' ? 'Post not found.' : 'Post no encontrado.'}</div>
      </div>
    )
  }

  const PostContent = post.component

  return (
    <div className="post">
      <div className="post_content">
        <div className="post_header">
          <h1>{post.meta.title}</h1>
          <span>{formattedDate(post.meta.date, dateLocale)}</span>
        </div>
        <div onClick={handleClick}>
          <PostContent />
        </div>
        <hr className="post_divider" />
        <div className="post_nav">
          {previousPost && (
            <Link
              to={`${linkPrefix}${previousPost.meta.slug}`}
              className="post_nav_link"
            >
              {lang === 'en' ? 'Previous' : 'Anterior'}:{' '}
              <span className="post_nav_link_title">
                {previousPost.meta.title}
              </span>
            </Link>
          )}
          {nextPost && (
            <Link
              to={`${linkPrefix}${nextPost.meta.slug}`}
              className="post_nav_link"
            >
              {lang === 'en' ? 'Next' : 'Siguiente'}:{' '}
              <span className="post_nav_link_title">{nextPost.meta.title}</span>
            </Link>
          )}
        </div>
        <div className="post_back">
          <Link to={backLink}>proxima</Link>
        </div>
      </div>
    </div>
  )
}

// src/pages/post/Post.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import { useRoute } from 'vue-router'
import { usePosts, type Lang } from '../../composables/usePosts'
import { formattedDate } from '../../utils/date'
import './Post.css'

const route = useRoute()
const lang = computed<Lang>(() => (route.meta.lang as Lang) ?? 'es')
const posts = computed(() => usePosts(lang.value))
const backLink = computed(() => (lang.value === 'en' ? '/en' : '/'))
const dateLocale = computed(() => (lang.value === 'en' ? 'en-US' : 'es-CL'))

const post = computed(() =>
  posts.value.find((p) => p.meta.slug === route.params.slug),
)

const linkPrefix = computed(() => (lang.value === 'en' ? '/en/' : '/'))

const currentIndex = computed(() =>
  posts.value.findIndex((p) => p.meta.slug === route.params.slug),
)

// posts are sorted newest-first, so "previous" (older) is the next index
// and "next" (newer) is the previous index
const previousPost = computed(() => posts.value[currentIndex.value + 1])
const nextPost = computed(() =>
  currentIndex.value > 0 ? posts.value[currentIndex.value - 1] : undefined,
)

const isFullscreen = ref(false)

function ClicEvent(event: MouseEvent) {
  const target = event.target as HTMLImageElement

  if (target.tagName === 'IMG') {
    isFullscreen.value = !isFullscreen.value
    document.body.style.overflow = isFullscreen.value ? 'hidden' : ''
    document.body.classList.toggle('enlarged', isFullscreen.value)
    target.classList.toggle('enlarged', isFullscreen.value)
  }
}
</script>

<template>
  <div class="post">
    <div v-if="post" class="post_content">
      <div class="post_header">
        <h1>{{ post.meta.title }}</h1>
        <span>{{ formattedDate(post.meta.date, dateLocale) }}</span>
      </div>
      <div @click="ClicEvent">
        <component :is="post.component" />
      </div>
      <hr class="post_divider" />
      <div class="post_nav">
        <RouterLink
          v-if="previousPost"
          :to="`${linkPrefix}${previousPost.meta.slug}`"
          class="post_nav_link"
        >
          {{ lang === 'en' ? 'Previous' : 'Anterior' }}:
          <span class="post_nav_link_title">{{ previousPost.meta.title }}</span>
        </RouterLink>
        <RouterLink
          v-if="nextPost"
          :to="`${linkPrefix}${nextPost.meta.slug}`"
          class="post_nav_link"
        >
          {{ lang === 'en' ? 'Next' : 'Siguiente' }}:
          <span class="post_nav_link_title">{{ nextPost.meta.title }}</span>
        </RouterLink>
      </div>
      <div class="post_back">
        <RouterLink :to="backLink">proxima</RouterLink>
      </div>
    </div>
    <div v-else>
      {{ lang === 'en' ? 'Post not found.' : 'Post no encontrado.' }}
    </div>
  </div>
</template>

<script lang="ts"></script>
