// src/App.tsx
import { Helmet } from 'react-helmet-async'
import NavBar from './components/navbar/NavBar'
import AppRoutes from './router'
import styles from './App.module.css'

export default function App() {
  return (
    <>
      <Helmet
        titleTemplate="%s | Proxima — Un blog personal"
        defaultTitle="Proxima — Un blog personal"
      />
      <NavBar />
      <div className={styles.container}>
        <AppRoutes />
      </div>
    </>
  )
}

// src/App.vue
<script setup lang="ts">
import NavBar from './components/navbar/NavBar.vue'
import { useHead } from '@unhead/vue'

useHead({
  title: 'Proxima — Un blog personal',
  titleTemplate: (title) =>
    title
      ? `${title} | Proxima — Un blog personal`
      : 'Proxima — Un blog personal',
})
</script>

<template>
  <NavBar />
  <div class="container">
    <RouterView />
  </div>
</template>

<style scoped>
.container {
  max-width: 632px;
  width: calc(100% - 32px);
  margin: 0 auto;
}
</style>
